//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blog: Blog;
  blogConnection: BlogConnection;
  pricing: Pricing;
  pricingConnection: PricingConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryPricingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPricingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};

export type DocumentFilter = {
  blog?: InputMaybe<BlogFilter>;
  pricing?: InputMaybe<PricingFilter>;
  homepage?: InputMaybe<HomepageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blog | Pricing | Homepage | Folder;

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title?: Maybe<Scalars['String']['output']>;
  seoTitle?: Maybe<Scalars['String']['output']>;
  description: Scalars['String']['output'];
  pubDate: Scalars['String']['output'];
  updatedDate?: Maybe<Scalars['String']['output']>;
  primaryKeyword?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  seoTitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  updatedDate?: InputMaybe<DatetimeFilter>;
  primaryKeyword?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type PricingJuneOffer = {
  __typename?: 'PricingJuneOffer';
  badge?: Maybe<Scalars['String']['output']>;
  message?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['String']['output']>;
  closingNote?: Maybe<Scalars['String']['output']>;
};

export type PricingPlans = {
  __typename?: 'PricingPlans';
  slug?: Maybe<Scalars['String']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  monthlyPrice?: Maybe<Scalars['Float']['output']>;
  sixMonthPrice?: Maybe<Scalars['Float']['output']>;
  rollingPrice?: Maybe<Scalars['Float']['output']>;
  setupFee?: Maybe<Scalars['Float']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  notIncluded?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type PricingFaq = {
  __typename?: 'PricingFaq';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type Pricing = Node & Document & {
  __typename?: 'Pricing';
  juneOffer?: Maybe<PricingJuneOffer>;
  plans?: Maybe<Array<Maybe<PricingPlans>>>;
  faq?: Maybe<Array<Maybe<PricingFaq>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PricingJuneOfferFilter = {
  badge?: InputMaybe<StringFilter>;
  message?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<StringFilter>;
  closingNote?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PricingPlansFilter = {
  slug?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  monthlyPrice?: InputMaybe<NumberFilter>;
  sixMonthPrice?: InputMaybe<NumberFilter>;
  rollingPrice?: InputMaybe<NumberFilter>;
  setupFee?: InputMaybe<NumberFilter>;
  featured?: InputMaybe<BooleanFilter>;
  features?: InputMaybe<StringFilter>;
  notIncluded?: InputMaybe<StringFilter>;
};

export type PricingFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type PricingFilter = {
  juneOffer?: InputMaybe<PricingJuneOfferFilter>;
  plans?: InputMaybe<PricingPlansFilter>;
  faq?: InputMaybe<PricingFaqFilter>;
};

export type PricingConnectionEdges = {
  __typename?: 'PricingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pricing>;
};

export type PricingConnection = Connection & {
  __typename?: 'PricingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PricingConnectionEdges>>>;
};

export type HomepageUrgencyBar = {
  __typename?: 'HomepageUrgencyBar';
  badge?: Maybe<Scalars['String']['output']>;
  message?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['String']['output']>;
  linkHref?: Maybe<Scalars['String']['output']>;
};

export type HomepageHero = {
  __typename?: 'HomepageHero';
  headline?: Maybe<Scalars['String']['output']>;
  headlineHighlight?: Maybe<Scalars['String']['output']>;
  subheadline?: Maybe<Scalars['String']['output']>;
};

export type HomepageLiveStats = {
  __typename?: 'HomepageLiveStats';
  sitesThisWeek?: Maybe<Scalars['Float']['output']>;
  inProgress?: Maybe<Scalars['Float']['output']>;
  launchedThisMonth?: Maybe<Scalars['Float']['output']>;
  latestLaunchName?: Maybe<Scalars['String']['output']>;
  latestLaunchUrl?: Maybe<Scalars['String']['output']>;
};

export type HomepageTestimonials = {
  __typename?: 'HomepageTestimonials';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
};

export type HomepageFaq = {
  __typename?: 'HomepageFaq';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  urgencyBar?: Maybe<HomepageUrgencyBar>;
  hero?: Maybe<HomepageHero>;
  liveStats?: Maybe<HomepageLiveStats>;
  testimonials?: Maybe<Array<Maybe<HomepageTestimonials>>>;
  faq?: Maybe<Array<Maybe<HomepageFaq>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageUrgencyBarFilter = {
  badge?: InputMaybe<StringFilter>;
  message?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<StringFilter>;
  linkHref?: InputMaybe<StringFilter>;
};

export type HomepageHeroFilter = {
  headline?: InputMaybe<StringFilter>;
  headlineHighlight?: InputMaybe<StringFilter>;
  subheadline?: InputMaybe<StringFilter>;
};

export type HomepageLiveStatsFilter = {
  sitesThisWeek?: InputMaybe<NumberFilter>;
  inProgress?: InputMaybe<NumberFilter>;
  launchedThisMonth?: InputMaybe<NumberFilter>;
  latestLaunchName?: InputMaybe<StringFilter>;
  latestLaunchUrl?: InputMaybe<StringFilter>;
};

export type HomepageTestimonialsFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type HomepageFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type HomepageFilter = {
  urgencyBar?: InputMaybe<HomepageUrgencyBarFilter>;
  hero?: InputMaybe<HomepageHeroFilter>;
  liveStats?: InputMaybe<HomepageLiveStatsFilter>;
  testimonials?: InputMaybe<HomepageTestimonialsFilter>;
  faq?: InputMaybe<HomepageFaqFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlog: Blog;
  createBlog: Blog;
  updatePricing: Pricing;
  createPricing: Pricing;
  updateHomepage: Homepage;
  createHomepage: Homepage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdatePricingArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingMutation;
};


export type MutationCreatePricingArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};

export type DocumentUpdateMutation = {
  blog?: InputMaybe<BlogMutation>;
  pricing?: InputMaybe<PricingMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blog?: InputMaybe<BlogMutation>;
  pricing?: InputMaybe<PricingMutation>;
  homepage?: InputMaybe<HomepageMutation>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  updatedDate?: InputMaybe<Scalars['String']['input']>;
  primaryKeyword?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PricingJuneOfferMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  message?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['String']['input']>;
  closingNote?: InputMaybe<Scalars['String']['input']>;
};

export type PricingPlansMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  monthlyPrice?: InputMaybe<Scalars['Float']['input']>;
  sixMonthPrice?: InputMaybe<Scalars['Float']['input']>;
  rollingPrice?: InputMaybe<Scalars['Float']['input']>;
  setupFee?: InputMaybe<Scalars['Float']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  notIncluded?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PricingFaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type PricingMutation = {
  juneOffer?: InputMaybe<PricingJuneOfferMutation>;
  plans?: InputMaybe<Array<InputMaybe<PricingPlansMutation>>>;
  faq?: InputMaybe<Array<InputMaybe<PricingFaqMutation>>>;
};

export type HomepageUrgencyBarMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  message?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['String']['input']>;
  linkHref?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageHeroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  headlineHighlight?: InputMaybe<Scalars['String']['input']>;
  subheadline?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageLiveStatsMutation = {
  sitesThisWeek?: InputMaybe<Scalars['Float']['input']>;
  inProgress?: InputMaybe<Scalars['Float']['input']>;
  launchedThisMonth?: InputMaybe<Scalars['Float']['input']>;
  latestLaunchName?: InputMaybe<Scalars['String']['input']>;
  latestLaunchUrl?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageTestimonialsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  urgencyBar?: InputMaybe<HomepageUrgencyBarMutation>;
  hero?: InputMaybe<HomepageHeroMutation>;
  liveStats?: InputMaybe<HomepageLiveStatsMutation>;
  testimonials?: InputMaybe<Array<InputMaybe<HomepageTestimonialsMutation>>>;
  faq?: InputMaybe<Array<InputMaybe<HomepageFaqMutation>>>;
};

export type BlogPartsFragment = { __typename: 'Blog', title?: string | null, seoTitle?: string | null, description: string, pubDate: string, updatedDate?: string | null, primaryKeyword?: string | null, heroImage?: string | null, readTime?: string | null, avatar?: string | null, body?: string | null };

export type PricingPartsFragment = { __typename: 'Pricing', juneOffer?: { __typename: 'PricingJuneOffer', badge?: string | null, message?: string | null, highlight?: string | null, closingNote?: string | null } | null, plans?: Array<{ __typename: 'PricingPlans', slug?: string | null, badge?: string | null, name?: string | null, tagline?: string | null, monthlyPrice?: number | null, sixMonthPrice?: number | null, rollingPrice?: number | null, setupFee?: number | null, featured?: boolean | null, features?: Array<string | null> | null, notIncluded?: Array<string | null> | null } | null> | null, faq?: Array<{ __typename: 'PricingFaq', question?: string | null, answer?: string | null } | null> | null };

export type HomepagePartsFragment = { __typename: 'Homepage', urgencyBar?: { __typename: 'HomepageUrgencyBar', badge?: string | null, message?: string | null, highlight?: string | null, linkHref?: string | null } | null, hero?: { __typename: 'HomepageHero', headline?: string | null, headlineHighlight?: string | null, subheadline?: string | null } | null, liveStats?: { __typename: 'HomepageLiveStats', sitesThisWeek?: number | null, inProgress?: number | null, launchedThisMonth?: number | null, latestLaunchName?: string | null, latestLaunchUrl?: string | null } | null, testimonials?: Array<{ __typename: 'HomepageTestimonials', name?: string | null, role?: string | null, badge?: string | null, image?: string | null, quote?: string | null } | null> | null, faq?: Array<{ __typename: 'HomepageFaq', question?: string | null, answer?: string | null } | null> | null };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title?: string | null, seoTitle?: string | null, description: string, pubDate: string, updatedDate?: string | null, primaryKeyword?: string | null, heroImage?: string | null, readTime?: string | null, avatar?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title?: string | null, seoTitle?: string | null, description: string, pubDate: string, updatedDate?: string | null, primaryKeyword?: string | null, heroImage?: string | null, readTime?: string | null, avatar?: string | null, body?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PricingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PricingQuery = { __typename?: 'Query', pricing: { __typename: 'Pricing', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, juneOffer?: { __typename: 'PricingJuneOffer', badge?: string | null, message?: string | null, highlight?: string | null, closingNote?: string | null } | null, plans?: Array<{ __typename: 'PricingPlans', slug?: string | null, badge?: string | null, name?: string | null, tagline?: string | null, monthlyPrice?: number | null, sixMonthPrice?: number | null, rollingPrice?: number | null, setupFee?: number | null, featured?: boolean | null, features?: Array<string | null> | null, notIncluded?: Array<string | null> | null } | null> | null, faq?: Array<{ __typename: 'PricingFaq', question?: string | null, answer?: string | null } | null> | null } };

export type PricingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingFilter>;
}>;


export type PricingConnectionQuery = { __typename?: 'Query', pricingConnection: { __typename?: 'PricingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PricingConnectionEdges', cursor: string, node?: { __typename: 'Pricing', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, juneOffer?: { __typename: 'PricingJuneOffer', badge?: string | null, message?: string | null, highlight?: string | null, closingNote?: string | null } | null, plans?: Array<{ __typename: 'PricingPlans', slug?: string | null, badge?: string | null, name?: string | null, tagline?: string | null, monthlyPrice?: number | null, sixMonthPrice?: number | null, rollingPrice?: number | null, setupFee?: number | null, featured?: boolean | null, features?: Array<string | null> | null, notIncluded?: Array<string | null> | null } | null> | null, faq?: Array<{ __typename: 'PricingFaq', question?: string | null, answer?: string | null } | null> | null } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, urgencyBar?: { __typename: 'HomepageUrgencyBar', badge?: string | null, message?: string | null, highlight?: string | null, linkHref?: string | null } | null, hero?: { __typename: 'HomepageHero', headline?: string | null, headlineHighlight?: string | null, subheadline?: string | null } | null, liveStats?: { __typename: 'HomepageLiveStats', sitesThisWeek?: number | null, inProgress?: number | null, launchedThisMonth?: number | null, latestLaunchName?: string | null, latestLaunchUrl?: string | null } | null, testimonials?: Array<{ __typename: 'HomepageTestimonials', name?: string | null, role?: string | null, badge?: string | null, image?: string | null, quote?: string | null } | null> | null, faq?: Array<{ __typename: 'HomepageFaq', question?: string | null, answer?: string | null } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, urgencyBar?: { __typename: 'HomepageUrgencyBar', badge?: string | null, message?: string | null, highlight?: string | null, linkHref?: string | null } | null, hero?: { __typename: 'HomepageHero', headline?: string | null, headlineHighlight?: string | null, subheadline?: string | null } | null, liveStats?: { __typename: 'HomepageLiveStats', sitesThisWeek?: number | null, inProgress?: number | null, launchedThisMonth?: number | null, latestLaunchName?: string | null, latestLaunchUrl?: string | null } | null, testimonials?: Array<{ __typename: 'HomepageTestimonials', name?: string | null, role?: string | null, badge?: string | null, image?: string | null, quote?: string | null } | null> | null, faq?: Array<{ __typename: 'HomepageFaq', question?: string | null, answer?: string | null } | null> | null } | null } | null> | null } };

export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  seoTitle
  description
  pubDate
  updatedDate
  primaryKeyword
  heroImage
  readTime
  avatar
  body
}
    `;
export const PricingPartsFragmentDoc = gql`
    fragment PricingParts on Pricing {
  __typename
  juneOffer {
    __typename
    badge
    message
    highlight
    closingNote
  }
  plans {
    __typename
    slug
    badge
    name
    tagline
    monthlyPrice
    sixMonthPrice
    rollingPrice
    setupFee
    featured
    features
    notIncluded
  }
  faq {
    __typename
    question
    answer
  }
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  urgencyBar {
    __typename
    badge
    message
    highlight
    linkHref
  }
  hero {
    __typename
    headline
    headlineHighlight
    subheadline
  }
  liveStats {
    __typename
    sitesThisWeek
    inProgress
    launchedThisMonth
    latestLaunchName
    latestLaunchUrl
  }
  testimonials {
    __typename
    name
    role
    badge
    image
    quote
  }
  faq {
    __typename
    question
    answer
  }
}
    `;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const PricingDocument = gql`
    query pricing($relativePath: String!) {
  pricing(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PricingParts
  }
}
    ${PricingPartsFragmentDoc}`;
export const PricingConnectionDocument = gql`
    query pricingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PricingFilter) {
  pricingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PricingParts
      }
    }
  }
}
    ${PricingPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    pricing(variables: PricingQueryVariables, options?: C): Promise<{data: PricingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingQueryVariables, query: string}> {
        return requester<{data: PricingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingQueryVariables, query: string}, PricingQueryVariables>(PricingDocument, variables, options);
      },
    pricingConnection(variables?: PricingConnectionQueryVariables, options?: C): Promise<{data: PricingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingConnectionQueryVariables, query: string}> {
        return requester<{data: PricingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingConnectionQueryVariables, query: string}, PricingConnectionQueryVariables>(PricingConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/28e16fde-214e-40bd-8535-e79b7f7d15c8/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  