import Stripe from 'stripe';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const envPath = join(__dir, '../.env');

// Parse .env
const env = Object.fromEntries(
  readFileSync(envPath, 'utf8')
    .split('\n')
    .filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => {
      const idx = l.indexOf('=');
      return [l.slice(0, idx).trim(), l.slice(idx + 1).trim()];
    })
);

const stripe = new Stripe(env.STRIPE_SECRET_KEY);

const PLANS = [
  {
    key: 'STARTER',
    name: 'Get Online',
    description: '5-page website, hosting, SSL, GA4, 2 content updates per month. Email support.',
    setupFee: 199,
    prices: { MONTHLY: 69, SIX: 59, ROLLING: 79 },
  },
  {
    key: 'GROWTH',
    name: 'Get Found',
    description: '8-page website, local SEO, 1 blog post/month, GBP management, 3 content updates, ranking report.',
    setupFee: 359,
    prices: { MONTHLY: 119, SIX: 99, ROLLING: 139 },
  },
  {
    key: 'PRO',
    name: 'Get Leads',
    description: '12-page website, full SEO management, 2 blog posts/month, GBP managed weekly, WhatsApp access.',
    setupFee: 599,
    prices: { MONTHLY: 169, SIX: 149, ROLLING: 189 },
  },
];

const TERM_LABELS = {
  MONTHLY: '3-month minimum',
  SIX: '6-month minimum',
  ROLLING: 'Rolling monthly',
};

async function run() {
  console.log('Creating Stripe products and prices...\n');
  const newEnvVars = {};

  for (const plan of PLANS) {
    // Subscription product
    const subProduct = await stripe.products.create({
      name: `Pixova ${plan.name}`,
      description: plan.description,
    });
    console.log(`✓ Product: Pixova ${plan.name} → ${subProduct.id}`);

    // Recurring prices (one per term)
    for (const [term, amount] of Object.entries(plan.prices)) {
      const price = await stripe.prices.create({
        product: subProduct.id,
        unit_amount: amount * 100,
        currency: 'gbp',
        recurring: { interval: 'month' },
        nickname: `${plan.name} - ${TERM_LABELS[term]}`,
      });
      const key = `STRIPE_PRICE_${plan.key}_${term}`;
      newEnvVars[key] = price.id;
      console.log(`  ✓ £${amount}/mo (${TERM_LABELS[term]}) → ${price.id}`);
    }

    // Setup fee product + one-time price
    const setupProduct = await stripe.products.create({
      name: `Pixova ${plan.name} - Setup Fee`,
      description: `One-time setup fee for the ${plan.name} plan. Paid when site goes live.`,
    });
    const setupPrice = await stripe.prices.create({
      product: setupProduct.id,
      unit_amount: plan.setupFee * 100,
      currency: 'gbp',
      nickname: `${plan.name} Setup Fee`,
    });
    const setupKey = `STRIPE_SETUP_${plan.key}`;
    newEnvVars[setupKey] = setupPrice.id;
    console.log(`  ✓ Setup fee £${plan.setupFee} (one-time) → ${setupPrice.id}\n`);
  }

  // Write new vars to .env
  let envContent = readFileSync(envPath, 'utf8').trimEnd();
  envContent += '\n\n# Pixova plan prices (generated by setup-stripe.mjs)\n';
  for (const [key, val] of Object.entries(newEnvVars)) {
    envContent += `${key}=${val}\n`;
  }
  writeFileSync(envPath, envContent);

  console.log('--- .env updated with new price IDs ---\n');
  for (const [k, v] of Object.entries(newEnvVars)) {
    console.log(`${k}=${v}`);
  }
  console.log('\nDone. Run the dev server and test checkout.');
}

run().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
